#file: noinspection SpringBootApplicationYaml
#数据库连接信息
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db_qk
    username: root
    password: 123456

    servlet:
      multipart:
        max-file-size: 10MB
        max-request-size: 10MB

  data:
    redis:
      host: localhost
      port: 6379
      client-type: lettuce
      database: 0




## 原来mybatis配置替换成MP配置
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true
  mapper-locations: com.qk.management.mapper/*.xml
  global-config:
    db-config:
      id-type: auto

### 阿里云OSS 自定义配置信息
aliyun:
  oss:
    endpoint: https://oss-cn-hangzhou.aliyuncs.com
    bucket-name: javaweb-rightsquare2025
    region: cn-hangzhou